implementing feature gates for apiserver
onmetal/matryoshka pull request #36
Opened 2022-01-19 11:21 UTC by nikhilbarge

# Proposed Changes

-
-
-

Fixes # 34

2022-01-26 08:40 UTC, adracus requested changes

2022-01-26 08:40 UTC, adracus commented on apis/matryoshka/v1alpha1/kubeapiserver_types.go
> +	FeatureGates   map[string]bool             `json:"featureGates"`
Please add some docstring here.

2022-01-26 08:40 UTC, adracus commented on controllers/matryoshka/internal/kubeapiserver/kubeapiserver.go
> -
Remove that change.

2022-01-26 08:40 UTC, adracus commented on controllers/matryoshka/internal/kubeapiserver/kubeapiserver.go
> +		featureGates = append(featureGates, key+"="+strconv.FormatBool(val))
Use `fmt.Sprintf` here

2022-01-26 08:40 UTC, adracus commented on controllers/matryoshka/internal/kubeapiserver/kubeapiserver.go
> +	featureGates := []string{}
Two things here:
1. Usually, you don't use `[]<type>` to initialize slices but rather the zero value `var []<type>`
2. The `featureGates` should be allocated with capacity equal to the length of the feature gates.

2022-01-26 08:41 UTC, afritzler commented on controllers/matryoshka/internal/kubeapiserver/kubeapiserver.go
> +		fmt.Sprintf("--feature-gates=%s", strings.Join(featureGates, ",")),
What should happen if the `featureGates` are not set?

2022-02-07 08:51 UTC, afritzler requested changes

2022-02-07 08:51 UTC, afritzler commented on controllers/matryoshka/internal/kubeapiserver/kubeapiserver.go
> +	var featureGates []string
Since we know the size of `server.Spec.FeatureGates` we can allocated the array with the correct size.

2022-02-07 10:40 UTC, afritzler requested changes

2022-02-07 10:40 UTC, afritzler commented on controllers/matryoshka/internal/kubeapiserver/kubeapiserver.go
> +	featureGates := make([]string, 0, len(server.Spec.FeatureGates))
As `capacity` is optional and derived from the `length` we can just use `make([]string, len(server.Spec.FeatureGates))`

2022-02-07 11:29 UTC, afritzler commented on controllers/matryoshka/internal/kubeapiserver/kubeapiserver.go
> +	featureGates := make([]string, 0, len(server.Spec.FeatureGates))
Forget about my suggestion! Please use length 0. Sorry for the commotion.

2022-02-07 12:10 UTC, afritzler approved these changes

2022-02-07 12:42 UTC, afritzler requested changes
We are currently missing a tests case for the featuregates flages.

2022-02-07 13:04 UTC, afritzler approved these changes

2022-02-07 15:18 UTC, merged